version: '3'
services:
  plgx-esp:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "6000:6000"
      - "5555:5555"
    depends_on:
      - rabbit1
      - postgres
    env_file:
      - .env
    environment:
      - POLYLOGYX_ENV=prod
    volumes:
         - carves:/src/plgx-esp/carves
    restart: always
    external_links:
      - rabbit1:rabbit1
      - postgres:postgres
  plgx-esp-ui:
    build:
      context: ./
      dockerfile: ./Dockerfile_ui
    ports:
      - "5001:5001"
    depends_on:
      - plgx-esp
    env_file:
      - .env
    environment:
      - POLYLOGYX_ENV=prod
    restart: always
    external_links:
      - rabbit1:rabbit1
      - postgres:postgres
    volumes:
         - carves:/src/plgx-esp-ui/resources/carves
         - yara:/src/plgx-esp-ui/resources/yara
  rabbit1:
    image: rabbitmq:3.6.5-management
    ports:
      - "15672:15672"
      - "5673:5673"
      - "5672:5672"
    volumes:
      #- rabbitmq:/var/lib/rabbitmq:rw
      - ./definitions.json:/opt/definitions.json:ro
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    restart: always
  nginx:
    image: "nginx:1.15.7-alpine"
    env_file:
      - .env
    depends_on:
      - plgx-esp
    external_links:
      - plgx-esp:plgx-esp
    volumes:
         - carves:/carves
         - ./nginx:/etc/nginx:ro
         - ./resources:/resources
         - ./dist:/dist
         - yara:/resources/yara
    command: >
          sh -c "nginx-debug -g 'daemon off;'"
    restart: always
    ports:
     - "9000:9000"
     - "5000:5000"
  postgres:
    image: "postgres:11.1"
    command: postgres -c 'max_connections=1000'
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  rsyslogf:
    build:
      context: ./rSysLogF
      dockerfile: Dockerfile
    ports:
      - "514:514"
    restart: always
volumes:
  postgres-data:
  carves:
  yara:
